import { Category } from 'types/category.interface';

export const categories: Category[] = [
  { id: 1, name: 'Romance', emoji: '❤️' },
  { id: 2, name: 'Ficção Científica', emoji: '🚀' },
  { id: 3, name: 'Fantasia', emoji: '🐉' },
  { id: 4, name: 'Mistério', emoji: '🕵️' },
  { id: 5, name: 'Suspense', emoji: '🔦' },
  { id: 6, name: 'Terror', emoji: '👻' },
  { id: 7, name: 'Clássicos', emoji: '🏺' },
  { id: 8, name: 'Contos', emoji: '📖' },
  { id: 9, name: 'Crônicas', emoji: '📜' },
  { id: 10, name: 'Poesia', emoji: '✒️' },
  { id: 11, name: 'Infantil', emoji: '🧸' },
  { id: 12, name: 'Juvenil', emoji: '🎒' },
  { id: 13, name: 'Biografia', emoji: '👤' },
  { id: 14, name: 'Memórias', emoji: '🗂️' },
  { id: 15, name: 'História', emoji: '🏛️' },
  { id: 16, name: 'Política', emoji: '🌍' },
  { id: 17, name: 'Filosofia', emoji: '💭' },
  { id: 18, name: 'Religião', emoji: '⛪' },
  { id: 19, name: 'Espiritualidade', emoji: '✨' },
  { id: 20, name: 'Psicologia', emoji: '🧠' },
  { id: 21, name: 'Autoajuda', emoji: '🌱' },
  { id: 22, name: 'Educação', emoji: '🎓' },
  { id: 23, name: 'Ciências Naturais', emoji: '🔬' },
  { id: 24, name: 'Ciências Sociais', emoji: '📊' },
  { id: 25, name: 'Saúde', emoji: '💊' },
  { id: 26, name: 'Bem-estar', emoji: '🧘' },
  { id: 27, name: 'Negócios', emoji: '💼' },
  { id: 28, name: 'Economia', emoji: '💵' },
  { id: 29, name: 'Tecnologia', emoji: '💡' },
];
